language: ruby
rvm:
  - 2.5

script: bundle exec jekyll build

deploy:
  provider: pages:git                 # Deployment typu Github Pages
  token: $GITHUB_TOKEN                # Zmienna środowiskowa z tokenem GH
  edge: true                          # Aktywacja dpl v2 on Travis CI
  local_dir: _site                    # Rezultat do opublikowania
  repo: KyrietS/kyriets.github.io     # Docelowe repozytorium, w którym publikuję
  target_branch: master               # Docelowa gałąź w docelowym repozytorium
  keep_history: true                  # Zachowywanie historii w docelowym repozytorium
  on:
    branch: master                    # Build dokonaj na gałęzi master w tym repozytorium
