language: ruby
rvm:
  - 2.5

script: bundle exec jekyll build

deploy:
  provider: pages
  local_dir: _site
  repo: KyrietS/kyriets.github.io
  target_branch: master
  token: $GITHUB_TOKEN
  keep_history: false
  on:
    branch: master
