= Blog - kod źródłowy (Jekyll)

Blog stworzony na podstawie autorskiego szablonu w Jekyll.

== Wymagania
* Ruby
* Gems / Rubygems
* Bundler

== Zbudowanie projektu
Aby wygenerować stronę lokalnie należy w katalogu głównym projektu uruchomić kolejno:

----
$ bundle install
$ bundle exec jekyll build
----

Strona statyczna zostanie wygenerowana w katalogu `_site`.

Zamiast budować stronę za każdym razem dobrze jest uruchomić automatyczne wprowadzanie zmian za pomocą polecenia:
----
$ bundle exec jekyll serve [-l,--liverealod]
----
Wtedy jekyll uruchomi serwer http pod lokalnym adresem.

*bundle exec jekyll* vs *jekyll* - jeśli w systemie zainstalowana jest tylko jedna wersja jekyll'a, to oba polecenia robia to samo. Pierwsze z nich jeśli uruchomione w katalogu głównym projektu, odczytuje wersję jekyll'a z `Gemfile` i uruchmia ją (tę odpowiednią).

== Automatyczne budowanie i publikowanie strony
Github Actions pozwala na zbudowanie projektu i wypchnięcie zawartości katalogu `_site` do repozytorium https://github.com/KyrietS/kyriets.github.io[KyrietS/kyriets.github.io], które następnie publikuje wszystkie znajdujące się tam pliki pod adresem: https://kyriets.github.io.

Każdy commit do tego repozytorium spowoduje zbudowanie i wypchnięcie gotowej strony w świat.

**Obecnie projekt nie korzysta już z Travis CI.**

CI od Travis pozwala na zbudowanie strony u nich w chmurze i automatyczne wysłanie zawartości folderu `_site` do repozytorium, na którym hostowany jest blog.
